---
title: "Pedestrian Crash Severity Modeling"
author: "Kirsten Johnson"
date: "5/10/2022"
output: 
github_document:
    toc: true
    toc_depth: 2
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
### Import libraries
library(gglm)
library(tidyverse)
library(dplyr)
library(devtools)
library(ggplot2)
library(rmarkdown)
library(leaflet)
library(ggthemes)
library(DAAG)
library(stats)
library(stargazer)
library(readr)
library(magrittr)
```



```{r}
### Import statewide pedestrian crash data 2017-2019 data and preview
pedcrashes<-read_csv("../Data/pedcrashes20172019.csv")
paged_table((pedcrashes))
```

```{r}
### Select fields of interest and preview
pedcrashes<-pedcrashes%>%
  select(crash_numb, max_injr_svrty_cl, drvr_cntrb_circ_cl, road_surf_cond_descr, road_cntrb_descr, traf_cntrl_devc_type_descr, ambnt_light_descr)
paged_table(head(pedcrashes))
```


```{r}
###Summarize fields of interest
summary(pedcrashes)
```


```{r}
### Identify unique values of Max Injury Severity Reported
table(select(pedcrashes, max_injr_svrty_cl))
```

```{r}
##Use case_when to create new field "injury_level" and mutate max_injr_svrty_cl into numeric scale using the KABCO injury classification scale
#### K=5, A=4, B=3, C=2, O=1
pedcrashes1<-pedcrashes%>%
  mutate(injury_level = case_when(
         max_injr_svrty_cl == "Fatal injury (K)" ~ 5,
         max_injr_svrty_cl == "Non-fatal injury - Incapacitating"~ 4,
         max_injr_svrty_cl == "Suspected Serious Injury (A)" ~ 4,
         max_injr_svrty_cl == "Non-fatal injury - Non-incapacitating" ~ 3,
         max_injr_svrty_cl == "Suspected Minor Injury (B)" ~ 3,
         max_injr_svrty_cl == "Non-fatal injury - Possible" ~ 2,
         max_injr_svrty_cl == "Possible Injury (C)" ~ 2,
         max_injr_svrty_cl == "No injury" ~ 1,
         max_injr_svrty_cl == "No Apparent Injury (O)" ~ 1,
         TRUE ~ -1))
  
pedcrashesgraph<-pedcrashes1%>%
  filter(injury_level != -1) %>%
  mutate(injury_label = case_when(
         injury_level == 5 ~ "Fatal injury (K)",
         injury_level == 4 ~ "Suspected Serious Injury (A)",
         injury_level == 3 ~ "Possible Injury (C)",
         injury_level == 2 ~ "Suspected Minor Injury (B)",
         injury_level == 1 ~ "No Apparent Injury (O)",
         TRUE ~ "NA"))
```

```{r}
### Create bar chart for crash severity distribution

barchart<-pedcrashesgraph%>%
  ggplot(aes(injury_label)) +geom_bar(stat="count",width=.7, fill="lightblue") +
  theme(axis.text.x = element_text(angle = 10, size= 13, vjust= 1, hjust=1))+ ### adjust x-axis label orientation
  geom_text(stat='count', aes(label=..count..), size= 6, vjust=1.6 )+ ### add count labels
  ggtitle("Massachusetts 2017-2019 Pedestrian Crashes by Crash Severity")+
  xlab("Crash Severity")+
  ylab("Number of Crashes")+
  theme(plot.title = element_text(size=22, face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

barchart
```

```{r}
### Export bar chart

ggsave("pedcrashbarchart.png", plot=barchart,width = 330, 
       height = 200, 
       units = "mm")
```

```{r}
##Use case_when to create new field "is_ka" and mutate max_injr_svrty_cl into dummy for 1= KA, 0 = not a KA crash

pedcrashes2<-pedcrashes1%>%
  mutate(is_ka = case_when(
         max_injr_svrty_cl == "Fatal injury (K)" ~ 1,
         max_injr_svrty_cl == "Non-fatal injury - Incapacitating"~ 1,
         max_injr_svrty_cl == "Suspected Serious Injury (A)" ~ 1,
         max_injr_svrty_cl == "Non-fatal injury - Non-incapacitating" ~ 0,
         max_injr_svrty_cl == "Suspected Minor Injury (B)" ~ 0,
         max_injr_svrty_cl == "Non-fatal injury - Possible" ~ 0,
         max_injr_svrty_cl == "Possible Injury (C)" ~ 0,
         max_injr_svrty_cl == "No injury" ~ 0,
         max_injr_svrty_cl == "No Apparent Injury (O)" ~ 0,
         TRUE ~ -1))

table(select(pedcrashes2, is_ka))
```

```{r}
### Identify unique values of Road Surface Condition description
table(select(pedcrashes, road_surf_cond_descr))

```



```{r}
### create dummy road_surface where 1 = road surface altered, 0 = dry road surface
pedcrashes3<-pedcrashes2%>%
  mutate(road_surface = case_when(
         road_surf_cond_descr == "Dry" ~ 0,
         road_surf_cond_descr == "Ice"~ 1,
         road_surf_cond_descr == "Sand, mud, dirt, oil, gravel"~ 1,
         road_surf_cond_descr == "Slush" ~ 1,
         road_surf_cond_descr == "Snow" ~ 1,
         road_surf_cond_descr == "Water (standing, moving)" ~ 1,
         road_surf_cond_descr == "Wet" ~ 1,
         road_cntrb_descr == "Road surface condition (wet, icy, snow, slush, etc.)" ~ 1,
         TRUE ~ -1))

table(select(pedcrashes3, road_surface))
```

```{r}
### Identify unique values of Road Contributing Circumstance Descriptions
table(select(pedcrashes, road_cntrb_descr))
```

```{r}
### create dummy road_circumstances where 1 = None , 0 = road contributing circumstance
pedcrashes4<-pedcrashes3%>%
  mutate(road_circumstances = case_when(
         road_cntrb_descr == "None" ~ 0,
         road_cntrb_descr == "Debris"~ 1,
         road_cntrb_descr == "Obstruction in roadway"~ 1,
         road_cntrb_descr == "Other" ~ 1,
         road_cntrb_descr == "Road surface condition (wet, icy, snow, slush, etc.)" ~ 0, ###coded 0 since value accounted for in road_surface
         road_cntrb_descr == "Rut, holes, bumps" ~ 1,
         road_cntrb_descr == "Shoulders (none, low, soft)" ~ 1,
         road_cntrb_descr == "Toll/booth/plaza related" ~ 1,
         road_cntrb_descr == "Traffic congestion related" ~ 1,
         road_cntrb_descr == "Traffic control device inoperative, missing, or obscured" ~ 1,
         road_cntrb_descr == "Work zone (construction/maintenance/utility)" ~ 1,
         road_cntrb_descr == "Worn, travel-polished surface" ~ 1,
         TRUE ~ -1))

table(select(pedcrashes4, road_circumstances))
```



```{r}
### Identify unique values of Ambient Light Descriptions
table(select(pedcrashes,ambnt_light_descr))
```

```{r}
### create dummy ambient_light where 1 = Daylight, 0 = Dark or potential lack of light
pedcrashes5<-pedcrashes4%>%
  mutate(ambient_light = case_when(
         ambnt_light_descr == "Dark - lighted roadway" ~ 0,
         ambnt_light_descr == "Dark - unknown roadway lighting"~ 0,
         ambnt_light_descr == "Dark - roadway not lighted" ~ 0,
         ambnt_light_descr == "Dawn" ~ 0,
         ambnt_light_descr == "Daylight" ~ 1,
         ambnt_light_descr == "Dusk" ~ 0,
         TRUE ~ -1))

table(select(pedcrashes5, ambient_light))
```


```{r}
### Identify unique values of Road Contributing Circumstance Descriptions
table(select(pedcrashes, traf_cntrl_devc_type_descr))
```

```{r}
### create dummy traffic_control_device where 1 = no traffic control device present, 0 = no traffic controls present
pedcrashes6<-pedcrashes5%>%
  mutate(traffic_control_device = case_when(
         traf_cntrl_devc_type_descr == "No controls" ~ 0,
         traf_cntrl_devc_type_descr == "Yield signs"~ 1,
         traf_cntrl_devc_type_descr == "Traffic control signal"~ 1,
         traf_cntrl_devc_type_descr == "Flashing traffic control signal" ~ 1,
         traf_cntrl_devc_type_descr == "Warning signs" ~ 1,
         traf_cntrl_devc_type_descr == "Railway crossing device" ~ 1,
         traf_cntrl_devc_type_descr == "Yield signs" ~ 1,
         traf_cntrl_devc_type_descr == "School zone signs" ~ 1,
         traf_cntrl_devc_type_descr == "Stop signs" ~ 1,
         TRUE ~ -1))

table(select(pedcrashes6, traffic_control_device))
```

```{r}
### Identify unique values of Driver Contributing Circumstance Descriptions
## Many values, remove comment to run: table(select(pedcrashes, drvr_cntrb_circ_cl))
```

```{r}
### create dummy traffic_control_device where 1 = at least 1 driver had improper driving, 0 = no improper driving for at least 1 driver, others may be unknown 
pedcrashes7<-pedcrashes6%>%
  mutate(improper_driving =  case_when(
    str_detect(drvr_cntrb_circ_cl, "speed limit") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "yield") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "too closely") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "improper turn") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "visibility") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Visibility") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "too fast") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Distracted") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Inattention") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "reckless") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "aggressive") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "steering") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Disregarded traffic signs") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Other improper action") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Swerving") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Glare") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Failure") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Illness") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Fatigue") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Emotional") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "History heart/epilepsy/fainting") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Wrong side or wrong way") ~ 1,
    str_detect(drvr_cntrb_circ_cl, "Physical impairment") ~ 1,
    TRUE ~ 0))

table(select(pedcrashes7, improper_driving))
```

```{r}
### Check if all driver contributing circumstances are captured, excluding defective equipment
filtercheck<-pedcrashes7%>%
  filter(improper_driving == 0) %>%
  paged_table()
table(select(filtercheck, drvr_cntrb_circ_cl))
```

```{r}
##Filter to only necessary fields
###Filter out unknowns for all variables and view data with relevant fields
pedcrashesclean<-pedcrashes7%>%
  select(injury_level, is_ka, road_surface, road_circumstances, ambient_light, traffic_control_device, improper_driving)%>%
  filter(traffic_control_device!= -1, na.rm= TRUE)

summary(pedcrashesclean)
```

```{r}
###Create Training data
set.seed(1)
trainingsetsize<-pedcrashesclean%>%
  nrow()%>%
  multiply_by(0.7)%>%
  round()
train_indices<-sample(1:nrow(pedcrashesclean), trainingsetsize)
train<-pedcrashesclean[train_indices,]
test<-pedcrashesclean[-train_indices,]
```




```{r}
ols_levels<-lm(injury_level ~ .-is_ka, data = train)
ols_binary<-lm(is_ka ~ .-injury_level, data = train)
```

```{r}
par(mfrow = c(2,3))
plot(ols_binary, which = 1:6)
```
```{r}
par(mfrow = c(2,3))
plot(ols_levels, which = 1:6)
```



```{r}
# backward elimination
step(object = ols_levels, # specify full model
     direction = "backward") # specify backward
```



```{r}
###test backwards elimination model
br_fit<-lm(formula = injury_level ~ ambient_light + traffic_control_device + improper_driving, data = train)
summary(br_fit)
```


```{r}
###Create and print diagnostics plots for backwards regression model
png("diagnosticsplots.png", width=15, height=6, units='in', res=300)
par(mfrow = c(1:2))
plot(br_fit, which=1:2, ask=FALSE)
dev.off()
```

```{r}
###Model Evaluation- run models using testing data, generate AIC, BIC, PRESS, MSE, RSME

predict(br_fit, test) %>% subtract(test$injury_level) %>%
  raise_to_power(2) %>% mean() -> MSE_br_fit
predict(ols_binary, test) %>% subtract(test$is_ka) %>%
  raise_to_power(2) %>% mean() -> MSE_ols_binary
predict(ols_levels, test) %>% subtract(test$injury_level) %>% 
  raise_to_power(2) %>% mean() -> MSE_ols_levels
Press1<-press(br_fit)
BIC1<-BIC(br_fit)
AIC1<-AIC(br_fit)
Press2<-press(ols_levels)
BIC2<-BIC(ols_levels)
AIC2<-AIC(ols_levels)
```

```{r}
###visualize metrics in table
cat('               ', " MSE", '      RMSE', '     PRESS','   AIC', '     BIC', '\n',
'Backwards Elim:', MSE_br_fit, sqrt(MSE_br_fit), Press1, AIC1, BIC1, '\n',
'All Predictors:', MSE_ols_levels, sqrt(MSE_ols_levels), Press2, AIC2,BIC2, '\n')
```

```{r}
stargazer(ols_levels, br_fit, title="Table 1. Regression Results",
dep.var.labels=c("Injury Severity Level"),
covariate.labels=c("Pavement Friction Impaired", "Road Contributing Circumstance",
"Ambient Light","Traffic Control Device","Improper Driving"),
column.labels=c("All Predictors","Backwards Elimination"),
add.lines=list(c("AIC", "11824.04", "11822.68"), c("BIC","11868.53","11854.45"), c("PRESS","4012.704","4011.383")),
type="text", out="stargazertable.txt", ci=TRUE, ci.level=0.05, single.row=TRUE)
```


```{r}
###Export stargazer as html too
stargazer(ols_levels, br_fit, title="Table 1. Regression Results",
dep.var.labels=c("Injury Severity Level"),
covariate.labels=c("Pavement Friction Impaired", "Road Contributing Circumstance",
"Ambient Light","Traffic Control Device","Improper Driving"),
column.labels=c("All Predictors","Backwards Elimination"),
add.lines=list(c("AIC", "11824.04", "11822.68"), c("BIC","11868.53","11854.45"), c("PRESS","4012.704","4011.383")),
type="html", out="stargazertable.html", ci=TRUE, ci.level=0.05, single.row=TRUE)
```











